== Ribbon Discovery in Kubernetes


调用微服务的Spring Cloud客户端应用程序应该对依赖客户端负载平衡感兴趣
功能，以便自动发现它可以到达给定服务的端点。这种机制一直是
在https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-ribbon[spring-cloud-kubernetes-ribbon]项目中实施，其中a
Kubernetes客户端填充包含信息的https://github.com/Netflix/ribbon[Ribbon]`ServerList`
关于这样的端点。

该实现是以下启动器的一部分，您可以通过将其依赖项添加到您的pom文件来使用它：
====
[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-ribbon</artifactId>
    <version>${latest.version}</version>
</dependency>
----
====

填充端点列表后，Kubernetes客户端将搜索所存在的已注册端点
通过匹配Ribbon Client注释中定义的服务名称来定义当前名称空间或项目，如下所示：
====
[source,java]
----
@RibbonClient(name = "name-service")
----
====

您可以通过在`application.properties`中提供属性来配置Ribbon的行为（通过您的应用程序）
专用`ConfigMap`）使用以下格式：`<服务名称> .ribbon。<功能区配置键>`，其中：
* `<name of your service>` 对应于您通过功能区访问的服务名称，使用
`@RibbonClient` annotation （例如前面例子中的`name-service`）。
* `<Ribbon configuration key>` 是由其定义的功能区配置键之一
https://github.com/Netflix/ribbon/blob/master/ribbon-core/src/main/java/com/netflix/client/config/CommonClientConfigKey.java[Ribbon's `CommonClientConfigKey` class].

此外，`spring-cloud-kubernetes-ribbon`项目还定义了两个额外的配置键
控制Ribbon如何与Kubernetes交互。特别是，如果端点定义了多个端口，则为默认端口
行为是使用第一个找到的。要更具体地选择在多端口服务中使用哪个端口，您可以使用
`PortName`键。如果要指定应在哪个Kubernetes命名空间中查找目标服务，则可以使用
“KubernetesNamespace”键，记住在这两个实例中用这些键作为服务名称和前缀
`ribbon`前缀，如前所述。

以下示例使用此模块进行功能区发现：

* link:./spring-cloud-kubernetes-examples/kubernetes-circuitbreaker-ribbon-example[Spring Cloud Circuitbreaker and Ribbon]
* https://github.com/fabric8-quickstarts/spring-boot-ribbon[fabric8-quickstarts - Spring Boot - Ribbon]
* https://github.com/fabric8io/kubeflix/tree/master/examples/loanbroker/bank[Kubeflix - LoanBroker - Bank]

注意：您可以通过在应用程序属性文件中设置`spring.cloud.kubernetes.ribbon.enabled = false`键来禁用功能区发现客户端。
